version: '3.8'
services:
  http-microservice:
    restart: always
    container_name: http-microservice
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    env_file:
      - ../../.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - mokalli

networks:
  mokalli:
    external: true
