version: '3.8'
services:
  microservice:
    container_name: microservice
    build:
      context: ../..
      dockerfile: docker/develop/Dockerfile
    volumes:
      - ../..:/src
    env_file:
      - ../../.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - mokalli

networks:
  mokalli:
    external: true
