version: '3.8'
services:
  public-gateway:
    container_name: public-gateway
    build:
      context: ../..
      dockerfile: docker/develop/Dockerfile
    volumes:
      - ../..:/src
    env_file:
      - ../../.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - mokalli

networks:
  mokalli:
    external: true
